version: '3.4'

services:
  webapi:
    image: your-dockerhub-username/your-project:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
      - minio
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings:DefaultConnection=Host=db;Database=Blog;Username=postgres;Password=azimjon2000;Port=5432
      - JwtSettings:Key=JWTRefreshTokenHIGHsecuredPasswordVVVp1OH7Xzyr
      - JwtSettings:Issuer=http://localhost:5000
      - JwtSettings:Audience=http://localhost:4200
      - JwtSettings:LifetimeInMinutes=120
      - JwtSettings:RefreshLifetimeInDays=7
      - MinioSettings:Endpoint=minio:9000
      - MinioSettings:AccessKey=your-access-key
      - MinioSettings:SecretKey=your-secret-key

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azimjon2000
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: your-access-key
      MINIO_ROOT_PASSWORD: your-secret-key
    ports:
      - "9000:9000"
    command: server /data
