version: '3.8'

services:
  webapi:
    image: azimjon2000/blog:latest
    build:
      context: ../..  # Harakatning yuqori papkasiga qaytish
      dockerfile: src/Blog.WebAPI/Dockerfile  # Dockerfile yo'li
    ports:
      - "5000:5000"
    depends_on:
      - db
      - minio
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=db;Database=Blog;Username=postgres;Password=azimjon2000;Port=5432
      JwtSettings__Key: JWTRefreshTokenHIGHsecuredPasswordVVVp1OH7Xzyr
      JwtSettings__Issuer: http://localhost:5000
      JwtSettings__Audience: http://localhost:4200
      JwtSettings__LifetimeInMinutes: 120
      JwtSettings__RefreshLifetimeInDays: 7
      MinioSettings__Endpoint: minio:9000
      MinioSettings__AccessKey: your-access-key
      MinioSettings__SecretKey: your-secret-key

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azimjon2000
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: your-access-key
      MINIO_ROOT_PASSWORD: your-secret-key
    ports:
      - "9000:9000"
    command: server /data
