name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: List all files
        run: ls -la 

      - name: Find deploy.yaml
        run: find . -name deploy.yaml   

      - name: List files in src
        run: ls -la ../../    
          
      - name: List all files
        run: ls -laR 

      - name: Find Dockerfile
        run: find . -name Dockerfile 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6

        with:
          context: .
          file: ./src/Blog.WebAPI/Dockerfile  
          push: true
          tags: azimjon2000/blog:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with Docker Compose
        run: |
            docker-compose -f ./docker-compose.yml up -d
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_EXPERIMENTAL: enabled
